---
name: Publish documentation to Notion

on:
  push:
    branches: [main]

# Run this only once at a time to avoid conflicts with Notion.
concurrency:
  group: ci
  cancel-in-progress: false

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build sample documentation
        run: |
          rm -rf ./build-sample
          uv run --extra=sample sphinx-build -W -b notion sample ./build-sample

      - name: Publish sample to Notion
        run: |
          uv run --all-extras notion-upload \
            --parent-page-id "${{ vars.NOTION_SAMPLE_PAGE_ID }}" \
            --file "./build-sample/index.json" \
            --title "Sphinx-Notionbuilder Sample" \
            --icon "üêç"
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: Build sample-warnings documentation
        run: |
          rm -rf ./build-sample-warnings
          uv run --extra=sample sphinx-build -W -b notion sample-warnings ./build-sample-warnings

      - name: Publish sample-warnings to Notion
        run: |
          uv run --all-extras notion-upload \
            --parent-page-id "${{ vars.NOTION_SAMPLE_PAGE_ID }}" \
            --file "./build-sample-warnings/index.json" \
            --title "Sphinx-Notionbuilder Suppressed Warnings Sample" \
            --icon "üêç"
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
